---
title: "Replication document for age-depth model of Ha Makotoko"
author: "W. Christopher Carleton"
output: pdf_document
---

## Load Necessary Libraries and Data
```{r}
library(Bchron)
library(ggplot2)
library(ggrepel)
library(tidyverse)

hm_data <- read.csv("../Data/HM_age_depth_isotopes.csv")

hm_data_bchron <- read.csv("../Data/HM_age_depth_bchron.csv")[-c(6),]

sample_depths <- hm_data$depth_m
sample_depths <- sample_depths[!is.na(sample_depths)]
interp_depth_range <- range(sample_depths)
interp_depths <- seq(0,
                    interp_depth_range[2],
                    0.01)
```

## Run Bchronology
```{r, echo=TRUE, results='hide'}
hm_agedepth <- Bchronology(ages = hm_data_bchron$c14age,
                            ageSds = hm_data_bchron$sd,
                            positions = hm_data_bchron$depth,
                            positionThicknesses = hm_data_bchron$thickness,
                            calCurves = hm_data_bchron$curve,
                            predictPositions = interp_depths,
                            extractDate = 1950 - 2009)
```

## Summarize the model
```{r}
hm_agedepth_mean <- apply(hm_agedepth$thetaPredict,
                        2,
                        mean)

hm_agedepth_quant <- t(apply(hm_agedepth$thetaPredict,
                            2,
                            quantile,
                            probs = c(0.05, 0.95)))

hm_agedepth_summary <- data.frame(Depth_m = interp_depths,
                                    Mean_YBP = hm_agedepth_mean,
                                    L05 = hm_agedepth_quant[, 1],
                                    U95 = hm_agedepth_quant[, 2])

hm_agedepth_summary_sample <- subset(hm_agedepth_summary,
                                    Depth_m %in% sample_depths)
```

## Write out results
```{r}
write.table(hm_agedepth_summary,
            file = "../Output/hm_agedepth_Bchron.csv",
            sep = ",",
            row.names = F)

write.table(hm_agedepth_summary_sample,
            file = "../Output/hm_agedepth_Bchron_sample.csv",
            sep = ",",
            row.names = F)

hm_data_with_agedepth <- merge(hm_data,
                            hm_agedepth_summary_sample,
                            by.x = 5,
                            by.y = 1)

write.table(hm_data_with_agedepth,
            file = "../Output/hm_agedepth_Bchron_sample_merged.csv",
            sep = ",",
            row.names = F)
```

## Plot the modelled tie-points
```{r}

df <- as.tibble(hm_agedepth$theta)
names(df) <- c("modern", hm_data_bchron$SampleID[-1])

tie_point_posteriors <- pivot_longer(df,
                                    everything(),
                                    names_to = "tie_point_id",
                                    values_to = "ybp_sample")

depth_labels <- data.frame(tie_point_id = names(df),
                            x = 40000, 
                            y = 0.9, 
                            depthlabel = paste(hm_data_bchron$depth,
                                                " ± 0.01",
                                                "m", 
                                                sep=""))

ggplot(tie_point_posteriors) +
    geom_histogram(aes(x = ybp_sample, y = ..ncount..),
                    alpha = 0.8,
                    binwidth = 100) +
    geom_text(data = depth_labels, 
                aes(x = x, y = y, label = depthlabel)) +
    facet_grid(tie_point_id ~ .) +
    labs(x = "Year BP\n(100 year bin width)", y = "Scaled Count") +
    theme_minimal()
ggsave(device = "pdf",
    file = "./Output/agedepth_Bchron_tiepoints.pdf",
    width = 10,
    height = 10,
    units = "cm",
    scale = 1.5)
```

## Plot the model
```{r}
ggplot(hm_agedepth_summary) +
    geom_ribbon(mapping = aes(xmin = L05, xmax = U95, y = Depth_m),
                fill = "steelblue") +
    geom_line(mapping = aes(y = Depth_m, x = Mean_YBP)) +
    geom_point(data = hm_agedepth_summary_sample,
            mapping = aes(y = Depth_m, x = Mean_YBP)) +
    geom_text_repel(data = hm_agedepth_summary_sample,
            mapping = aes(y = Depth_m, x = Mean_YBP, label = Depth_m),
            nudge_x = 2000) +
    labs(x = "Year BP",
        y = "Depth (m)") +
    scale_y_reverse() +
    scale_x_reverse() +
    theme_minimal()
ggsave(device = "pdf",
    file = "../Output/agedepth_Bchron.pdf")
```
